meta:
  environment: ~

update:
  canaries: 1
  max_in_flight: 50
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000
  serial: false

jobs:
  - name: cron
    templates:
    - name: cron
      release: cron
    instances: 1
    persistent_disk: 0
    resource_pool: small_z1
    networks:
      - name: cron1
        default: [dns,gateway]
        static_ips:
        - 10.250.2.55

networks:
#resource_pools: ~
properties:
  cron:
    variables: # a key-value map of any environment variables you want set in the crontab
      VAR1: val1
      VAR2: val2
    entries: # a list of key-value objects representing cron entries
    - command:  echo "hello" > /etc/crond.d/soufian.txt # on peut lanceer une commande : commmande (( properties.cron.variables.VAR1 ;; a verifier)) var 2 ...
      minute: '1'
#     hour: '*'
#      day: '*'
#      month: '*'
#      wday: '*'