meta:
  environment: ~

update:
  canaries: 1
  max_in_flight: 50
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000
  serial: false

jobs:
  - name: bosh_backup_cron
    templates:
    - name: cron
      release: cron
    instances: 1
    persistent_disk: 0
    resource_pool: small_z1
    networks:
      - name: cron1
        default: [dns,gateway]
        static_ips:
        - 10.250.2.55

networks:
#resource_pools: ~
properties:
  cron:

